# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔/
  #分类: /categories/
  相册: /instagram

# SubNav
subnav:
  github: "https://github.com/1016990109"
  weibo: "http://weibo.com/u/3571600800"
  rss: "/atom.xml"
  #zhihu: "#"
  #douban: "#"
  #mail: "1016990109@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

tags: /tags

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico		

#你的头像url
avatar: /img/user.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: hcw13
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Vboars的博客: http://kass.top/


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
